pulibrary/pul-it-handbook

- README.md
- projects/prerequisites.md
Definition of what all VMs will have
> initial commit

- services/prerequisites.md
Thanks for bringing that up @cwulfman
> one must not always assume https

- README.md
- services/ansible.md
- services/prerequisites.md
The documentation thus far alludes to but doesn't exclusively mention
what is managing the hardware
> add ansible instructions

- README.md
- services/orangelight-indexing.md
Closes pulibrary/marc_liberation#322
> adds link to orangelight indexing doc

- services/mariadb.md
These are the steps to restart our mariadb cluster and fixes https://github.com/pulibrary/pul-the-hard-way/issues/22
> how to restart mariadb

- services/solr_restoration.md
Scenario on restoring solr2 by moving applications from solr3. 
closes #27
> [WIP] Google doc on how to restore applications in a different solr

- README.md
- services/solr.md
The local firewall is no longer enabled.
> none of the solr servers have a firewall enabled on them

- services/deployment.md
> Flesh out pulbot / heaven docs

- services/smtp-mail-server.md
> Add some info about our smtp server

- services/figgy.md
> Add steps to re-install simple-tiles

- README.md
- services/letsencrypt.md
these are the steps to update cicognara SSL certs.
> add lets encrypt files to load balancer

- services/ngixplus.md
Instructions contain how to open up the ssh tunnel for the admin console
> Adding instructions nginx plus

- services/cas.md
@kevinreiss and I went through installing Devise/Cas in the approvals gem.  This documents the steps we needed to go through to get it working.
> Adding instructions for cas

- README.md
- services/aws.md
Co-authored-by: Eliot Jordan <eliotj@princeton.edu>
> Add a page for AWS

- services/create_ssl_certs.md
Also change around the structure to make it easier to follow
> Change to use a variable

- services/lib-sftp.md
Closes https://github.com/pulibrary/bibdata/issues/855
Cron installed and tested on lib-sftp.
> Create lib-sftp cron job documentation

- services/deployment.md
> Update pulbot deployment location

- services/create_ssl_certs.md
- services/gce_backup.md
- add google cloud documentation
- these notes lack the CN. It will sometimes fail to run if not provided
> add common name

- services/create_ssl_certs.md
Fixes weird quotes in command (and a typo)
> Fixes weird quotes in command (and a typo)

- README.md
It was out of date.
closes #87
> Remove list of services from README

- services/create_ssl_certs.md
After creating a private key and certs, putting my "gotchas" into the docs - mostly to "remember to save a copy of the un encrypted private key".
Also, tidying up the page - capitalizations, making all the verbs agree, etc.
> Update cert docs

- services/shibboleth.md
How to establish a new Shibboleth SP endpoint at PUL.
Fixes https://github.com/pulibrary/pul-the-hard-way/issues/95
> Guide to installing Shibboeth SP

- gitmessage.md
Adds my profile info for attribution on future Refactorama commits.
> adds alicia as a collaborator

- services/shibboleth.md
Work toward https://github.com/pulibrary/rdss-catchall/issues/37
> Debugging shibboleth attributes

- services/cas.md
> Updated CAS integration notes

- gitmessage.md
also arranged alphabetically by last name
> add Rebecca from CDH

- README.md
- norms/inclusive_language.md
> Added norms directory and inclusive language entry, and updated README

- services/deployment.md
it's apparently using libdeploy now, not appdeploy
> Update webhooks link

- services/saml_vendor.md
I wrote down a few things I learned about configuring SAML authentication.
> adds detail to the SAML intro

- services/vpn.md
refs pulibrary/pulfalight#1183
> Update vpn documentation to include a couple more sources of IPs

- services/rapid7.md
We hope this will be helpful as we begin to install Rapid7 on our servers per OIT requirements.
> documents what we know about Rapid7

- gitmessage.md
Prevented Alicia's avatar to display
> Alicia's co-authored message needs a space

- services/nginxplus.md
@leefaisonr @sandbergja @christinach and I ran the nginx playbook to deploy some new certs and keys and remove some unused ones. This updates the documentation on nginx to reflect the steps we followed. I hope this will make everyone feel more comfortable and confident running the nginx playbook!
> adds details to nginx documentation

- services/nginxplus.md
Allow you to update on the config files on nginx plus
> Add Limit update_conf

- README.md
> Add links to team handbooks

- services/aws.md
Co-authored-by: Francis Kayiwa <kayiwa@users.noreply.github.com>
> Adding way to allow additional IPs to AWS

- workshops.txt
Coming out of shared goals planning, we may not have the same goal but there are some places we can collaborate and stay in communication.
> A place to collect and share workshops we develop or attend

- services/cas.md
I tried following these instructions and [it didn't work](https://github.com/pulibrary/tiger-data-app/pull/63).
I tried again, with the same result. I then compared my non-functional PR with the [PR that introduced CAS for pdc_describe](https://github.com/pulibrary/pdc_describe/pull/45/) and found a couple parts that are missing, and [now it works](https://github.com/pulibrary/tiger-data-app/pull/65).
> Add missing steps to CAS directions

- services/archive-pulbot.md
- services/deployment.md
Also moving pulbot instructions to an archive
fixes https://github.com/pulibrary/pul-it-handbook/issues/159
> Documenting the new tower deployment

- training-curriculum/css.md
- training-curriculum/databases.md
- training-curriculum/git.md
- training-curriculum/html-accessibility.md
- training-curriculum/javascript.md
- training-curriculum/rails.md
- training-curriculum/ruby-rspec.md
- training-curriculum/web-foundations.md
* Add headings
* Add link text
* Miscellaneous small edits
> Formatting and small updates to the training curriculum

- gitmessage.md
> Include Liz in the gitmessage

- gitmessage.md
> add sean warren to git message file

- training-curriculum/ruby-rspec.md
The video currently in the curriculum is good, but the audio is muffled and there are no captions.  The proposed replacement has better audio, captions, and covers some motivations for using RSpec that aren't included in the original video.
> Replacing a TDD video in the curriculum

- services/solr.md
Adds information on diagnosing Solr issues as well as a description of the data center constraints. I hope this documentation will help us recover more quickly from future outages, and give everyone on the team some tools for diagnosing issues with our Solr infrastructure.
> adds details from our recent Solr issues

- training-curriculum/rails.md
The track included all the html, css, javascript, and ruby videos which
we don't do in the same order.
> Replace treehouse track with individual rails videos

- services/panos_fw.md
the first section is a walk through to create a rule and the second one
is an untested how to add rules to Service Portal
> [panos] firewall rules

- services/panos_fw.md
Reorganizes our notes into step-by-step instructions with examples. This could still use some refinement, but it's better than it was.
> updates to firewall documentation based on today's run-through

- student-software-developers/administration-handbook.md
- student-software-developers/requirements-and-policies.md
- student-software-developers/student-handbook.md
Content taken from:
- [the interview agenda](https://docs.google.com/document/d/1FP_rFAEOmLpvatypPoWs8TMG8AXs4yeiaCBvJHVMKus/edit#heading=h.s01a78yi1g67)
- feedback from the student retrospective
- email communications with the Davis International Center
> [student developers] Add a page about requirements and policies

- services/disk_lvm_expansion.md
@kayiwa taught me this command when fixing a full-disk issue yesterday. I won't remember it, so I thought I'd add it to the documentation.
> adds troubleshooting info for lvms

- student-software-developers/administration-handbook.md
- student-software-developers/administration-handbook/all-hands.md
- student-software-developers/administration-handbook/campus-housing.md
- student-software-developers/administration-handbook/it-suite-access.md
- student-software-developers/administration-handbook/jobx.md
- student-software-developers/administration-handbook/laptops.md
- student-software-developers/administration-handbook/offboarding.md
- student-software-developers/administration-handbook/recruitment.md
- student-software-developers/administration-handbook/timeline/01-january.md
- student-software-developers/administration-handbook/timeline/02-february.md
- student-software-developers/administration-handbook/timeline/03-march.md
- student-software-developers/administration-handbook/timeline/04-april.md
- student-software-developers/administration-handbook/timeline/05-may.md
- student-software-developers/administration-handbook/timeline/06-june.md
- student-software-developers/administration-handbook/timeline/08-august.md
- student-software-developers/administration-handbook/timeline/11-november.md
- student-software-developers/administration-handbook/timeline/12-december.md
Previously found at https://docs.google.com/document/d/1CeL_FQz5Xpr6vYXa3CzUrK3dhdfLEFnTZPAP-RfVU84/edit
> Migrate Student Dev Admin Handbook

- norms/inclusive_language.md
Reflecting updated terminology in use for post incident review discussions
> Added post incident review

- services/postgresql.md
Removes references to Figgy running on Postgres 10.
Attempts to reflect the current state of our postgresql infrastructure.
> updates psql docs

- gitmessage.md
make it easier to add Jaymee as a co-author
Co-authored-by: Jaymee Hyppolite <jaymeeh@users.noreply.github.com>
> add Jaymee to gitmessage

- services/disk_lvm_expansion.md
Co-authored-by: Francis Kayiwa <kayiwa@users.noreply.github.com>
> add commands to expand initial thin provisioned disk

- services/decommissioning.md
This should be a checklist of things to do when a server retires to the country. Some of the items are not yet clear to me, please fill in the gaps if you can!
> Document the steps for decommissioning servers

- student-software-developers/administration-handbook/resume-selection.md
- student-software-developers/administration-handbook/roles.md
- student-software-developers/administration-handbook/timeline/01-january.md
- student-software-developers/administration-handbook/timeline/02-february.md
@carolyncole Here are some suggestions; I thought it would be easier to just take a pass. Let me know what you think thank you!
> Suggest specific edits

- security/security_tools.md
This report is the result of our - @jrgriffiniii @sandbergja @christinach - investigation on security tools as part of the security goal for 2023.
> Add report on security tools.

- student-software-developers/administration-handbook/recruitment.md
These instructions work whether or not you are listed as a contact person in the job posting.
> [student dev] Document how to find a jobX id

- gitmessage.md
this adds John K to possible collaborators
> add John K to co-authored

- services/passenger.md
Ref https://github.com/pulibrary/orcid_princeton/issues/124
> Add more tips to the upgrading bundler instructions

- services/cas.md
... until we can figure out what changes are needed to support omniauth-cas 3.x
Ref https://github.com/pulibrary/orcid_princeton/issues/127
> Document the need for omniauth-cas 2.x

- services/checkmk.md
There's lots to add, but at least we know where the logs are.
> bare bones documentation for CheckmK

- gitmessage.md
Co-authored-by: Alicia Cozine <acozine@users.noreply.github.com>
Co-authored-by: Vickie Karasic <vickiekarasic@users.noreply.github.com>
> remove favour 

- services/decommissioning.md
Add a step to remember to revoke certificates
> revoke ACME certificates

- services/gce_bucket.md
- services/gce_service_account.md
- services/mariadb/maria_backup.sh
- services/mariadb/mysql_cnf
- services/postgresql/common.sh
- services/postgresql/full_pg_backup.sh
- services/postgresql/pg_backup.sh
- services/postgresql/prune.sh
- services/postgresql/push.sh
- services/restic_backup.md
related to https://github.com/pulibrary/princeton_ansible/issues/4193
> Restic backup

- operations-fellows/README.md
- operations-fellows/programming_languages.md
- operations-fellows/step_0.md
- operations-fellows/step_1.md
- operations-fellows/step_2.md
- operations-fellows/step_3.md
- operations-fellows/step_4.md
- operations-fellows/step_5.md
- operations-fellows/step_5_5.md
- operations-fellows/step_6.md
- **create a simple template with structure for the curriculum**
- **mention of treehouse**
> ops fellowship

- operations-fellows/README.md
- operations-fellows/programming_languages.md
- operations-fellows/step_0.md
add bash and linux in the base requirements
> add linux commands

- services/decommissioning.md
adds information about removing references to decommissioned VMs in our load balancer configs, variables, and in our inventory
> add steps to remove references to decommissioned VMs

- services/postgresdb_load_data.md
> Document how to pg_dump data from a production DB and load them to a staging DB

- services/nginxplus.md
the steps needed to set up HA for our loadbalancers
> add instructions on how to set up the HA

- services/nginxplus.md
- **add instructions on how to set up the HA**
- **full path to ha-setup binary**
> nginxplus HA

- services/new_vms_for_devs.md
As a developer, I have sometimes been unclear on:
1. What information Ops needs in order to build a new VM
2. What state I can expect that VM to be in when Ops says "here you go!"
3. What further steps are needed to get my application "up" and ready for prime time
This documentation attempts to answer these questions for developers.
> Information for developers on new VMs

- services/smtp-mail-server.md
related to https://github.com/pulibrary/princeton_ansible/pull/4980
> new mail relay

- student-software-developers/administration-handbook/jobx.md
discussed in today's student mentor checkin
> [student devs] Clarify info about emails from timesheetx

- gitmessage.md
we have a new collaborators :tada: Adding Brionna
Co-authored-by: Max Kadel <maxkadel@users.noreply.github.com>
Co-authored-by: Vickie Karasic <vickiekarasic@users.noreply.github.com>
> add brionna to collaborators

- services/checkmk.md
refs https://github.com/pulibrary/orcid_princeton/issues/182
> Update checkmk.md to include adding host via ansible

- services/solr_restoration.md
We were pointing to an ancient google doc about Solr2 and Solr3.
Point to the recently updated documentation!
> update the link for documenting solr restoration

- norms/production_application_checklist.md
Special thanks to all of IT for their contributions to this document.
> Add production application checklist

- services/dspace.md
We ran into an issue with dataspace today - after the OS package updates, it did not come back up. Here's some documentation about what we learned. Please add more details, folks!
> adds troubleshooting details for dspace

- services/veeam_restore.md
this is example documentation for how to run a restore of a file
Co-authored-by: John Kazmierski <jkazmier-PUL@users.noreply.github.com>
> [veeam] test file restore

- services/service_now_account.md
ref ticket: https://github.com/pulibrary/rdss-catchall/issues/137
> Add Princeton Service Now Account instructions

- services/nginxplus.md
- services/private_network.md
add steps for using our staging loadbalancer
document migration to private network
> include staging loadbalancers

- services/panos_fw.md
> add double space line breaks

- services/nginxplus.md
Give full name of dev load balancer for ssh (this is how it works for me)
> Use full name of dev load balancer for ssh/tunnel

- services/ezproxy.md
the ACME will renew the certificates but the ezproxy application needs
a manual process
> [ezproxy] cert renewal

- services/service_account.md
OIT has created a new Service Account Creation web wizard. The
application process will allow one to create an account. Most of our use
cases will be Application API YMMV
> New service account URI

- services/tower.md
When trying to debug what is going on the tower vms we couldn't readily know where to look
add a note about where to look for ansible-tower logs
> debug logs

- gitmessage.md
Co-authored-by: Angel Ruiz <aruiz1789@users.noreply.github.com>
Co-authored-by: Francis Kayiwa <kayiwa@users.noreply.github.com>
Co-authored-by: Vickie Karasic <vickiekarasic@users.noreply.github.com>
> Add Angel Ruiz to gitmessage

- services/new_vms_for_devs.md
- services/nginxplus.md
Note, there were some instances I did not change in
/services/private_network.md
> Update most uses of lib-adc to adc-prod

- student-software-developers/administration-handbook/resume-selection.md
Thanks to @hectorcorrea for the tip about Preview!
> [student dev] Add info about how to redact info

- services/solr.md
**Adapted from https://github.com/pulibrary/pdc_discovery/blob/main/docs/solr-mismatch.md
> Document how to update solr collection replication factor

- services/solr.md
> Add instructions for altering replica count in the Solr UI

- gitmessage.md
> Add Precilla to gitmessage

- services/create_ssl_certs.md
part of https://github.com/pulibrary/princeton_ansible/issues/6351
> [certs] geotaste hostname
