pulibrary/pul-it-handbook

services/service_now.md
Service Now is an integral part of our work. However, we face some challenges using it. It does not have the most intuitive interface. We use it infrequently enough that it's tough to develop habits and known pathways. And we only touch a very small subset of its enormous contents.
These instructions should help Future Us find the Service Now tickets we need, and enable us to follow up on things like SSL certs.
=> adds some Service Now tips and tricks

services/create_ssl_certs.md
Blocked until https://github.com/pulibrary/princeton_ansible/pull/2979 is merged. 
Adds links back to the Ansible playbook that automates the first step of the cert-renewal process.
=> adds reference to Ansible playbook

norms/inclusive_language.md
We want to avoid equating deletion of digital objects to human death.
See notes from cross-team meeting on 1/6/2024 for more background.
=> Deprecate "Tombstone" and recommend "DeletionMarker"

services/ansible.md, services/tower.md
First round of documentation about Ansible Tower. This PR:
- Updates the documentation about Ansible.
- Adds a page of documentation about Tower, including
- updating a project
- updating an inventory
- Tower testing for playbooks under development
Still to do:
- Document creating a Template in more detail, including how to add and enable Surveys. 
- Gather feedback, document other tasks as needed.
=> Add Tower docs

services/new_mac_setup.md
The link provided was great, but many of the commands were out of date.
=> Replace out-of-date link with our own documentation

services/deployment.md
I was working on https://github.com/pulibrary/princeton_ansible/issues/3847 and I could not remember where the Slack apps are configured. I looked here first. An hour later I finally remembered / found the place, so I'm adding this link to speed the process in future.
=> add link to slack apps site for Future Me

services/nginxplus.md
This is the practice we typically follow, but it wasn't mentioned in the documentation.
=> Nginx plus playbook docs: add a note about notifying in slack

training-curriculum/javascript.md
Using fetch is preferred over XmlHttpRequest.  Fetch is covered later in the curriculum, and the XmlHttpRequest is quite long.
=> [curriculum] Remove XmlHttpRequest

services/postgresql.md
Adds links to our Google Cloud storage for psql backups and information about the cron jobs that run our backups.
Next steps involve adding information about restoring from a backup.
=> adds psql backup info

services/create_ssl_certs.md
We now manage most of our certificates on the load balancers directly.
The new docs describe our new process and keep a generalized version of the old documentation for creating certs for domains that either don't end in .princeton.edu or are not served from the load balancers.
=> update docs on cert management to reflect our new system

services/vpn.md
Regine and Anna went through the instructions and found that neither of
our current global protect IPs were in the resulting list. Maybe the
list of domains isn't kept current?
=> Add a warning to the vpn list instructions

services/tower.md
We are running Platform 2.4 on RHEL 9!
This PR:
- Updates the names in our documentation to match the new Tower.
- Describes how to create and update custom EEs.
- Adds a section describing how we installed the new version of Tower.
=> Update tower docs

services/disk_lvm_expansion.md
Amends our existing documentation for expanding disks:
- adds a "Cheatsheet" with copy/paste-able commands that match the current LV/VG names
- adds an overview of the steps in order
- adds a section for diagnostics and confirmation
- separates out the longer "the hard way" section
- updates the output sections and commands in "the hard way" section to match current names
- does some general editing
=> adds a cheatsheet for disk expansion, updates names, some tidying

gitmessage.md
The [git project recommends using imperative mood](https://git.kernel.org/pub/scm/git/git.git/tree/Documentation/SubmittingPatches?h=v2.36.1#n181) in its own commit messages.
=> [gitmessage] Add commit message specifics

README.md
Also, update DACS and DLS handbook links to point to the jekyll/ github pages versions.
=> Add link text to the team handbook links

training-curriculum/html-accessibility.md
* Updates the link to treehouse's updated Intro to HTML and CSS -- thanks to @vh8154 for pointing out the update!
* Updates DACS handbooks links to point to the new jekyll version of the handbook
=> [training curriculum] Update links in the HTML curriculum

services/new_vms_for_devs.md
Changes the link in the documentation about adding new VMs. Previously the link went to the home page of the Prancible repo. This PR would make it open the 'create a new vm' ticket template in that repo.
=> Streamlines new-VM ticket creation

services/checkmk.md
Part of clearing our path to production for CheckMK.
Documents how to set up the LDAP connection between CheckMK and the campus LDAP system. Also adds documentation about the git repo and the quick command for restarting the server.
=> Adds draft docs on configuring authN/authZ for CheckMK

services/pul_kicker.md
Now that we can reboot VMs from Tower, adding that to the docs.
Plus a few edits.
=> update kicker docs, add link to Tower template for staging reboots

services/aws.md
Adds information about which group controls AWS access and who can manage that group's membership list.
=> document SSO setup for AWS

services/create_ssl_certs.md
Most of our certificates live on the load balancer and get auto-renewed with letsencrypt, but some do not. 
This PR aims to document the "oddball" certs - what they do, how to renew them, how to deploy them. ~~Still very much WIP.~~
Let's get this much merged, we can add as we go.
=> docs on certs not on the LB

services/shibboleth.md
I was looking for the Shibboleth request form today, found this documentation, clicked on the link and got a "The page you are looking for could not be found" error. I'm guessing a ServiceNow upgrade moved things. The updated link worked for me today - please test, though.
=> Update link to ServiceNow form for shibboleth

services/tower.md
Today @christinach and I built a new execution environment for the Wapiti reports. We followed the documentation here and found a couple of ways to improve it for next time.
=> adds some details to the 'build an EE' step in the Tower documentation

security/alma_api_key_management.md
Related to: https://github.com/PrincetonUniversityLibrary/security/issues/77
=> [Security] Add link to confluence page alma api key management

services/create_ssl_certs.md
OpenBSD has an `acme-client` which uses the ACME protocol to contact the
Letsencrypt Certificate Authority. It saves the files at
`/etc/ssl` and `/etc/ssl/private`
We use a cron job that runs at midnight and 0100 hours to contact and
renew the certificates when needed.
=> TLS for CDH

services/private_network.md
Builds on #321.
Divides the migration into three phases:
- the private network/IP space
- the .lib domain
- the staging loadbalancers
Provides rationale for each migration step.
Provides separate instructions for each migration step.
=> Expand network migration docs

README.md
Alphabetized Links and removed "developer"
=> add a link to Ops handbook

services/upgrading_major_versions.md
Add instructions for upgrading major versions. This is particularly relevant for Rails Applications or other applications that have working load balancer health checks.
=> Add instructions for upgrading major versions

services/upgrading_major_versions.md
You can limit deploys via capistrano using a flag! Thanks @carolyncole for the info!
=> Update deploy instructions for major version changes

services/restic_backup.md
Only one server per cluster does backups. Document this fact for Future Us.
=> update documentation for restic backups

services/checkmk.md
The existing documentation contained the command for restarting `cmk`. However, that is not always enough.
This PR adds the command for restarting `omd` and a note about rebooting if need be.
=> Add details about restarting CheckMK
